project_id = "napgcbrouifczxblteuw"

[functions.categories]
verify_jwt = false

[functions.items]
verify_jwt = false

[functions.lunch-today]
verify_jwt = false

[functions.delivery]
verify_jwt = false

[functions.orders]
verify_jwt = false

[functions.ai-session]
verify_jwt = false

[functions.log-message]
verify_jwt = false

[functions.menu]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.admin-users-update]
verify_jwt = true

[functions.admin-users-remove]
verify_jwt = true

[functions.settings]
verify_jwt = false

[functions.whatsapp-recebido]
verify_jwt = false

[functions.whatsapp-enviar]
verify_jwt = false

[functions.create-order-from-ai]
verify_jwt = false
